---
version: '3.8'
services:
  nginx-deploy:
    image: nginx:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
    ports:
    - "80:80"
    networks:
    - nginx-network
networks:
  nginx-network:
    driver: overlay
